const bebidas = [
    { id: 123, marca: "Villa del sur", tamanio: "500 cc", tipo: "Agua mineral", formato: "Botella", imagen: "./assets/villa-del-sur-botella.jpg", precio: 200 },
    { id: 234, marca: "Bonaqua", tamanio: "500 cc", tipo: "Agua mineral", formato: "Botella", imagen: "./assets/bonaqua-botella.webp", precio:  150 },
    { id: 345, marca: "Villavicencio", tamanio: "500 cc", tipo: "Agua mineral", formato: "Botella", imagen: "./assets/villavicencio-botella.webp", precio:  220 },
    { id: 456, marca: "Glaciar", tamanio: "500 cc", tipo: "Agua mineral", formato: "Botella", imagen: "./assets/glaciar-botella.webp", precio:  170 },
    { id: 567, marca: "Eco de los Andes", tamanio: "500 cc", tipo: "Agua mineral", formato: "Botella", imagen: "./assets/eco-de-los-andes-botella.webp", precio:  200 },
    { id: 789, marca: "Heineken", tamanio: "500 cc", tipo: "Cerveza", formato: "Lata", imagen: "./assets/heineken-lata.webp", precio: 600 },
    { id: 321, marca: "Heineken", tamanio: "1 litro", tipo: "Cerveza", formato: "Botella", imagen: "./assets/heineken-botella.webp", precio:  1200 },
    { id: 432, marca: "Stella Artois", tamanio: "500 cc", tipo: "Cerveza", formato: "Lata", imagen: "./assets/stella-artois-lata.webp", precio:  600 },
    { id: 543, marca: "Stella Artois", tamanio: "1 litro", tipo: "Cerveza", formato: "Botella", imagen: "./assets/stella-artois-botella.jpg", precio:  1200 },
    { id: 654, marca: "Quilmes", tamanio: "500 cc", tipo: "Cerveza", formato: "Lata", imagen: "./assets/quilmes-lata.png", precio:  550 },
    { id: 765, marca: "Quilmes", tamanio: "1 litro", tipo: "Cerveza", formato: "Botella", imagen: "./assets/quilmes-botella.webp", precio: 1000 },
    { id: 987, marca: "Brahma", tamanio: "500 cc", tipo: "Cerveza", formato: "Lata", imagen: "./assets/brahma-lata.jpg", precio:  450 },
    { id: 111, marca: "Brahma", tamanio: "1 litro", tipo: "Cerveza", formato: "Botella", imagen: "./assets/brahma-botella.jpg", precio: 800 },
    { id: 222, marca: "Coca Cola", tamanio: "330 cc", tipo: "Gaseosa", formato: "Lata", imagen: "./assets/coca-cola-original-lata.jpg", precio:  350 },
    { id: 333, marca: "Coca Cola", tamanio: "1.5 litros", tipo: "Gaseosa", formato: "Botella", imagen: "./assets/coca-cola-original-botella.jpg", precio: 800 },
    { id: 444, marca: "Sprite", tamanio: "330 cc", tipo: "Gaseosa", formato: "Lata", imagen: "./assets/sprite-lata.jpg", precio: 300 },
    { id: 555, marca: "Sprite", tamanio: "1.5 litros", tipo: "Gaseosa", formato: "Botella", imagen: "./assets/sprite-botella.jpg", precio: 700 },
    { id: 666, marca: "Paso de los toros Pomelo", tamanio: "330 cc", tipo: "Gaseosa", formato: "Lata", imagen: "./assets/paso-de-los-toros-lata.jpg", precio:  300 },
    { id: 777, marca: "Paso de los toros Pomelo", tamanio: "1.5 litros", tipo: "Gaseosa", formato: "Botella", imagen: "./assets/paso-de-los-toros-botella.jpg", precio:  700 },
    { id: 888, marca: "Villavicencio", tamanio: "500 cc", tipo: "Agua con gas", formato: "Botella", imagen: "./assets/villavicencio-con-gas.jpg", precio:+ 250 },
    { id: 999, marca: "Eco de los Andes", tamanio: "500 cc", tipo: "Agua con gas", formato: "Botella", imagen: "./assets/eco-de-los-andes-con-gas.webp", precio:  220 },
    { id: 787, marca: "Chivas", tamanio: "1 litro", tipo: "Whisky", formato: "Botella", imagen: "./assets/chivas-regal.webp", precio:  7000 },
    { id: 121, marca: "Johnnie Walker Red Label", tamanio: "1 litro", tipo: "Whisky", formato: "Botella", imagen: "./assets/red-label.jpeg", precio: 12000 },
    { id: 232, marca: "Johnnie Walker Black Label", tamanio: "1 litro", tipo: "Whisky", formato: "Botella", imagen: "./assets/black-label.jpg", precio:  20000 },
    { id: 343, marca: "Johnnie Walker Blue Label", tamanio: "1 litro", tipo: "Whisky", formato: "Botella", imagen: "./assets/blue-label.jpg", precio:  90000 },
    { id: 454, marca: "Trumpeter Malbec", tamanio: "1 litro", tipo: "Vino", formato: "Botella", imagen: "./assets/vino-trumpeter.jpg", precio:  7000 },
    { id: 565, marca: "Nicassia Malbec", tamanio: "1 litro", tipo: "Vino", formato: "Botella", imagen: "./assets/vino-nicasia.jpg", precio: 6500 }]